name: jarvis_app
description: "JARVIS Assistant App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  table_calendar: ^3.1.1
  audioplayers: ^6.1.0
  file_picker: ^8.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  file_picker: ^8.1.4
